name: Production Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy-web:
    name: Deploy Web Production
    uses: ./.github/workflows/deploy-web.yml
    with:
      environment: production
    secrets: inherit

  deploy-api:
    name: Deploy API Production
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: production
    secrets: inherit
